GET http://localhost:5000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaW5obnAiLCJpYXQiOjE2MjM1MTcxNzcsImV4cCI6MTYyMzUxNzIwN30.WsCSLQNz5kpfGbaaOygBLxgdYlCyLqYjjRh9HCe79NI
###

POST http://localhost:5500/login
Content-Type: application/json

{
  "username": "thinhnp"
}

###
POST http://localhost:5500/refreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaW5obnAiLCJpYXQiOjE2MjM1MTcwNTB9.ZsCORGsvplfZ0n0gNYAiYr3Uaw6RvnR1fFCcq6o5Fpc"
}

###
POST http://localhost:5500/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaW5obnAiLCJpYXQiOjE2MjM1MTcwNTB9.ZsCORGsvplfZ0n0gNYAiYr3Uaw6RvnR1fFCcq6o5Fpc"
}